export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const FETCH_ALL_EMPLOYEES = 'FETCH_ALL_EMPLOYEES';
export const FETCH_ALL_EMPLOYEES_SUCCESS = 'FETCH_ALL_EMPLOYEES_SUCCESS';
export const FETCH_ALL_EMPLOYEES_FAILURE = 'FETCH_ALL_EMPLOYEES_FAILURE';
